### ISSUE TITLE
Research on types

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-subquery#156]
### Problem

Currently the staging project configuration is done within https://github.com/sora-xor/sora-subquery/tree/staging-block-2000000-upd-dependencies. This branch was forked from the original one (https://github.com/sora-xor/sora-subquery/tree/sora-staging); dependencies were updated; handlers added. With the types unchanged, Subquery run from this branch still can't bypass a block, which is around `2006000`, which, in turn, could be bypassed with the project on old dependencies.

It's worth noticing the Polkadot.js implementation of SORA types (https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/soraSubstrate.ts). But once trying to reuse this method following the  official docs (https://academy.subquery.network/build/manifest/polkadot.html#custom-chains) the project is failing with the errors.

### DOD

- [ ] Subquery project with updated specs is running without errors from block 2000000 on staging
- [ ] Subquery project with updated specs is running without errors from block 7000000 on prod
- [ ] Subquery project on the older blocks (both prod and staging)

### Tasks

- [x] #263
- [ ] Alternative indexing solutions on the problematic blocks
  - [x] #232
  - [x] #238
- [x] #233
